pools:
  - 

spot:
  venues: 
    - "Binance"
  #  - "Aster"

futures:
  venues: 
    -

version_name: "v0.0.0_test"
strategy_id: 999
strategy_name: "dev strategy"

database:
  postgres:
    Host: "localhost"
    Port: 5432
    Name: "test_database"
    

  redis:
    Host: "localhost"
    Port: 6379
